services:
  - type: web
    name: mern-expense-tracker
    env: node
    rootDir: server
    buildCommand: |
      cd ../client && npm install && npm run build
      npm install
    startCommand: node index.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000 